leeader_mpc:
  leader:
    ros__parameters:
      control_horizon: 1
      prediction_horizon: 5
      dt: 0.1
      formation_dt: 0.1
      click_gain: 1
      leader_ns: "sweepee_1"
      is_omni: false
      base_footprint: "base_footprint"
      base_link:  "base_link"
      tool_frame: "tool0"
      map_frame: "map"
      joints:
        - "movex"
        - "movey"
        - "moverz"
        - "joint1"
        - "joint2"
        - "joint3"
        - "joint4"
        - "joint5"
        - "joint6"
      command_joints:
        - "joint1"
        - "joint2"
        - "joint3"
        - "joint4"
        - "joint5"
        - "joint6"
      control_interface:
        - ""
      state_interface:
        - ""
      robot_description_topic: "robot_description"
      cmd_vel_topic: "cmd_vel"
      scaling:
        active: true
        limit: 2
      fake_base_urdf: ""
      hierarchy: [1,2,3]
      trj_leader_topic: "trj_share"
      plan_topic: "/plan"
      followers:
        names:
          - "sweepee2"
        nax:
          - 9
        trj_topic:
          - "trj_fwl_share"
        trj_tollerance:
          - 0.1
