controller_manager:
  ros__parameters:
    update_rate: 100

    leader_mpc:
      type: formation_mpc/LeaderMPC

    leader_joint_bcast:
      type: joint_state_broadcaster/JointStateBroadcaster

leader_joint_bcast:
  ros__parameters:
    use_local_topics: True
    joints:
      - "joint_x"
      - "joint_y"
      - "joint_rz"
      - "ur/shoulder_pan_joint"
      - "ur/shoulder_lift_joint"
      - "ur/elbow_joint"
      - "ur/wrist_1_joint"
      - "ur/wrist_2_joint"
      - "ur/wrist_3_joint"

leader_mpc:
  ros__parameters:
    control_horizon_in_s: 2.0
    number_of_points: 10
    dt: 0.01
    formation_dt: 0.1
    cartesian_axis: [true, true, true, true, true, true]
    clik:
      gain: 1.7
      active: true
    pid:
      P: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
    action_monitor_rate: 100.0
    leader_ns: "leader"
    mobile_base_link: "base_link"
    manipulator_base_link: "ur/base_link"
    tool_frame: "ur/tool0"
    map_frame: "map"
    mount_frame: "mount_frame"
    object_frame: "object"
    joints:
      base:
        - "joint_x"
        - "joint_y"
        - "joint_rz"
      arm:
        - "ur/shoulder_pan_joint"
        - "ur/shoulder_lift_joint"
        - "ur/elbow_joint"
        - "ur/wrist_1_joint"
        - "ur/wrist_2_joint"
        - "ur/wrist_3_joint"
    command_interface:
#      - "velocity"
      - "position"
    state_interface:
      - "position"
      - "velocity"
    cmd_vel_topic: "cmd_vel"
    cartesian_task_weight:
      active: true
      weight: 1.0
    scaling: 1.0
    trj_leader_topic: "trj_share"
    plan_topic: "/plan"
    base_max_vel: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0]
    fake_base:
      package: "cooperative_transport_cell"
      path: "urdf/fake_base.urdf"
